## Import functions 

In [1]:
import os 
import sys
import numpy as np
#os.chdir(os.path.join("/home/datawork-osmose/",'osmoseNotebooks_v0','source'))

with open('path_codes.txt') as f:
    codes_path = f.readlines()[0]
os.chdir(os.path.join(codes_path))

from use_network_functions import load_model_hyperparameters
from use_network_functions import show_epoch_loss, set_epoch
from launcher_datasetScale import list_datasets
from apply_model_on_new_dataset import apply_model_on_new_dataset_main
from check_files_in_ai_folders import check_available_ai_tasks_benchmark_modeltrainned, check_available_file_resolution, check_available_formats_from_dataset

In [2]:
check_available_ai_tasks_benchmark_modeltrainned()

/
TaskTEST1/
    BMTEST1_1/
        models/
            model1/
            model2/
            model3/
TaskTEST2/
    BMTEST1_1/
        models/
            model1/
WeakDetection_1/
    Glider_PBW/
        models/
            model1/
            model_test/
Task_tutoMathieu/
    BM1/
        models/
            model1/


#### <span style="color:red">*Select your task and benchmark among those already created*</span>

Ex : 
- ``Task_ID`` = 'TaskTEST1'
- ``BM_Name`` = 'BMTEST1_1'
- ``VersionName`` = 'model1' 

In [3]:
Task_ID = 'TaskTEST1'
BM_Name = 'BMTEST1_1'
VersionName = 'model2'

## Print Parameters

#### <span style="color:blue">*JUST RUN CELL*</span>

In [ ]:
show_epoch_loss(Task_ID, BM_Name, Version_name)

In [ ]:
ID_epoch_for_evaluation = 4

set_epoch(Task_ID, BM_Name, Version_name, ID_epoch_for_evaluation)set_epoch(Task_ID, BM_Name, Version_name, ID_epoch_for_evaluation)

In [4]:
parameters = load_model_hyperparameters(Task_ID, BM_Name, VersionName)

for item in list(parameters.keys()):
    print(item, ' : ', parameters[item])

TrainsetRatio  :  0.8
batch_size  :  5
learning_rate  :  0.0001
num_epochs  :  20
shuffle  :  True
use_pretrained  :  False
input_data_format  :  audio
nfft  :  [1024, 1024]
window_size  :  [1024, 1024]
overlap  :  [50, 50]
dynamic_min  :  [-40, -40]
dynamic_max  :  [40, 40]
scaling  :  ['spectrum', 'spectrum']
num_classes  :  2
sample_rate  :  [48000 48000]
dataset_ID_tab  :  ['MPSU_ForestouHuella' 'MPSU_ForestouHuella_copy']
Task_ID  :  TaskTEST1
BM_Name  :  BMTEST1_1
SplitName  :  SPLIT2
Version_name  :  model2
ModelName  :  CNN3_FC1


#### <span style="color:red">*Select the dataset on which you want to apply the network*</span>

Ex : 
- ``Task_ID`` = 'TaskTEST1'
- ``BM_Name`` = 'BMTEST1_1'
- ``VersionName`` = 'model1' 

In [5]:
list_datasets()

Available datasets:
  - Glider
  - MPSU_ForestouHuella
  - MPSU_ForestouHuella_copy


In [6]:
dataset_ID = 'MPSU_ForestouHuella'

In [7]:
check_available_file_resolution(dataset_ID)
#CheckAvailableAnnotation(dataset_ID)
print('__________')
check_available_formats_from_dataset(dataset_ID)

Dataset :  MPSU_ForestouHuella
Available Resolution (LengthFile_samplerate) :
    
    30_48000
__________
_______________
Dataset :  MPSU_ForestouHuella
Available Spectrogram Format (nfft_windowsize_overlap) :
  1024_1024_50/


In [8]:
LenghtFile = [30]
sample_rate = [48000]

#### <span style="color:red">*Select format and spectrogram resolution*</span>

Nb : As list, same dimension as the dataset_ID_tab. 

Ex :
Format - MUST BE FROM LIST
- ``LenghtFile`` = 50 (in seconds) - FROM LIST
- ``sample_rate`` = 44100 (in hertz) - FROM LIST

Spectrogram Resolution : 
- if from list only those 3 :
    - ``nfft`` = 1024
    - ``window_size`` = 1024
    - ``overlap`` = 50
- if not from list, new spectrograms will be computed at each iteration, so we need more parameters : 
    - ``nfft`` = 1024
    - ``window_size`` = 1024
    - ``overlap`` = 50
    - ``dynamic_min`` = -30
    - ``dynamic_max`` = 30
    - ``scaling`` = 'spectrum'



In [9]:
input_data_format = 'spectrogram' #'audio' ou 'spectrogram'
# 'spectrogram' : use already computed spectrogram
# 'audio' : use .wav file, spectrogram will be computed iteratively

# File Format
LenghtFile = 30
sample_rate = 48000

#Spectrogram resolution
nfft = 1024
window_size = 1024
overlap = 50

dynamic_min = -40
dynamic_max = 40
scaling = 'spectrum'

In [10]:
application_parameters = {'input_data_format':input_data_format, 'nfft':nfft, 'window_size':window_size, 'overlap':overlap, 'dynamic_min':dynamic_min, 'dynamic_max':dynamic_max, 'scaling':scaling, 'LenghtFile':LenghtFile, 'sample_rate':sample_rate}

In [11]:
apply_model_on_new_dataset_main(dataset_ID, Task_ID, BM_Name, VersionName, application_parameters)

Done
F:/PhD/OSMOSE_TYPE_v2/dataset\MPSU_ForestouHuella\processed\spectrogram\30_48000\1024_1024_50\matrix\


  0%|          | 5/8895 [00:02<59:40,  2.48it/s]  

tensor([[0.9972, 0.1948]], device='cuda:0', grad_fn=<SigmoidBackward0>)
tensor([[0.9980, 0.1261]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.1114, 0.4588]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.9964, 0.1423]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.9978, 0.1669]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.1928, 0.5823]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.9981, 0.1617]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.9976, 0.1502]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)


  0%|          | 13/8895 [00:02<18:00,  8.22it/s]

tensor([[0.1559, 0.5018]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.9979, 0.1966]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.9983, 0.1207]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.1519, 0.5299]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.9984, 0.1815]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.9980, 0.1311]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.1279, 0.4637]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.9983, 0.1451]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)


  0%|          | 23/8895 [00:03<08:33, 17.27it/s]

tensor([[0.9979, 0.1222]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.1219, 0.4437]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.9971, 0.1791]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.9984, 0.1327]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.1083, 0.4720]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.9972, 0.1892]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.9983, 0.1348]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.1477, 0.4887]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)


  0%|          | 32/8895 [00:03<05:50, 25.31it/s]

tensor([[0.9967, 0.1575]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.9974, 0.1410]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.1044, 0.4688]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.9979, 0.1198]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.9973, 0.1659]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.1751, 0.5831]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.9980, 0.1699]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.9982, 0.1335]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)


  0%|          | 41/8895 [00:03<04:42, 31.39it/s]

tensor([[0.1602, 0.4502]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.9982, 0.1532]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.9984, 0.1264]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.1061, 0.4520]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.9984, 0.1289]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.9972, 0.1288]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.1598, 0.4186]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.9977, 0.1515]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.9983, 0.1517]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)


  1%|          | 50/8895 [00:03<04:10, 35.35it/s]

tensor([[0.1293, 0.4657]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.9976, 0.1328]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.9965, 0.1628]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.1835, 0.6008]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.9981, 0.1641]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.9981, 0.1643]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.2007, 0.5556]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.9979, 0.1663]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.9980, 0.1688]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)


  1%|          | 59/8895 [00:04<03:56, 37.34it/s]

tensor([[0.1439, 0.5317]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.9974, 0.1493]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.9979, 0.1830]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.1316, 0.4518]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.9972, 0.1269]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.9975, 0.1293]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.1236, 0.4761]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.9979, 0.1346]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.9964, 0.1315]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)


  1%|          | 68/8895 [00:04<03:42, 39.70it/s]

tensor([[0.1650, 0.5864]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.9976, 0.1266]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.9974, 0.1559]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.1538, 0.5515]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.9956, 0.1741]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.9972, 0.1391]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.2012, 0.6729]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.9975, 0.1523]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.9980, 0.1151]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)


  1%|          | 73/8895 [00:04<03:41, 39.79it/s]

tensor([[0.1172, 0.4731]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.9984, 0.2012]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.9979, 0.1444]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.1042, 0.5041]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.9975, 0.1964]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.9986, 0.1944]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.1131, 0.4336]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.9975, 0.1771]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.9962, 0.1225]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)


  1%|          | 83/8895 [00:04<03:33, 41.36it/s]

tensor([[0.2246, 0.5116]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.9963, 0.1715]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.9980, 0.1437]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.2912, 0.5161]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.9955, 0.1663]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.9983, 0.1115]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.2261, 0.6467]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.9977, 0.1631]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.9975, 0.1232]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)


  1%|          | 93/8895 [00:04<03:47, 38.70it/s]

tensor([[0.1128, 0.5678]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.9981, 0.1460]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.9954, 0.1705]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.2608, 0.5900]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.9980, 0.2040]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.9980, 0.1880]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.1313, 0.4120]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.9979, 0.1519]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.9987, 0.1486]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)


  1%|          | 103/8895 [00:05<03:40, 39.81it/s]

tensor([[0.1387, 0.3641]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.9978, 0.1641]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.9977, 0.1249]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.2168, 0.4875]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.9977, 0.1261]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.9952, 0.1304]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.2900, 0.5735]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.9985, 0.1701]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.9979, 0.1544]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)


  1%|▏         | 113/8895 [00:05<03:34, 40.96it/s]

tensor([[0.1672, 0.5537]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.9977, 0.1126]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.9987, 0.1149]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.1695, 0.4930]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.9980, 0.1825]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.9984, 0.1286]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.2019, 0.4920]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.9978, 0.1572]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.9981, 0.1711]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)


  1%|▏         | 118/8895 [00:05<03:36, 40.62it/s]

tensor([[0.1698, 0.5350]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.9961, 0.1563]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.9976, 0.1995]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.2426, 0.6205]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.9961, 0.1641]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.9986, 0.1546]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.1885, 0.5294]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.9971, 0.1923]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.9976, 0.1563]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)


  1%|▏         | 128/8895 [00:05<03:31, 41.42it/s]

tensor([[0.2640, 0.5720]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.9962, 0.2089]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.9960, 0.1593]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.3422, 0.6460]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.9979, 0.1838]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.9978, 0.1456]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.1278, 0.5497]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.9977, 0.1254]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)


  2%|▏         | 138/8895 [00:05<03:44, 38.97it/s]

tensor([[0.9980, 0.1661]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.1821, 0.5277]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.9961, 0.1749]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.9974, 0.1423]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.2941, 0.5242]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.9968, 0.1725]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.9968, 0.1416]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.2633, 0.6135]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)


  2%|▏         | 143/8895 [00:06<03:37, 40.27it/s]

tensor([[0.9967, 0.1941]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.9965, 0.1709]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.3409, 0.5641]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.9976, 0.1489]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.9968, 0.1272]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.3053, 0.6374]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.9977, 0.1422]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.9986, 0.1735]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)


  2%|▏         | 153/8895 [00:06<03:39, 39.89it/s]

tensor([[0.2187, 0.5594]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.9974, 0.1905]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.9985, 0.1299]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.1239, 0.4958]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.9984, 0.1391]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.9975, 0.1481]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.2023, 0.5922]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.9981, 0.1486]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.9973, 0.1555]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)


  2%|▏         | 158/8895 [00:06<05:59, 24.27it/s]


tensor([[0.1807, 0.4345]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.9983, 0.1722]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)
tensor([[0.9976, 0.1375]], device='cuda:0',
       grad_fn=<DifferentiableGraphBackward>)


KeyboardInterrupt: 